<?php

// НЕ ТРОГАТЬ ЕСЛИ НЕ ЗНАЕШЬ ЧТО ЭТО ТАКОЕ И ЗАЧЕМ ОНО НУЖНО
return [
    'accepted' => \Engine\Core\Validation\Rules\Core\Accepted::class,
    'alpha' => \Engine\Core\Validation\Rules\Core\Alpha::class,
    'alphadash' => \Engine\Core\Validation\Rules\Core\Alphadash::class,
    'alphanum' => \Engine\Core\Validation\Rules\Core\Alphanum::class,
    'blank' => \Engine\Core\Validation\Rules\Core\Blank::class,
    'card_scheme' => \Engine\Core\Validation\Rules\Core\CardScheme::class,
    'date' => \Engine\Core\Validation\Rules\Core\Date::class,
    'date_time' => \Engine\Core\Validation\Rules\Core\DateTime::class,
    'email' => \Engine\Core\Validation\Rules\Core\Email::class,
    'each_passed' => \Engine\Core\Validation\Rules\Core\EachPassed::class,
    'equal_to' => \Engine\Core\Validation\Rules\Core\EqualTo::class,
    'first_passed' => \Engine\Core\Validation\Rules\Core\FirstPassed::class,
    'greater_than' => \Engine\Core\Validation\Rules\Core\GreaterThan::class,
    'greater_than_or_equal' => \Engine\Core\Validation\Rules\Core\GreaterThanOrEqual::class,
    'identical_to' => \Engine\Core\Validation\Rules\Core\IdenticalTo::class,
    'inn' => \Engine\Core\Validation\Rules\Core\Inn::class,
    'ip' => \Engine\Core\Validation\Rules\Core\Ip::class,
    'is_false' => \Engine\Core\Validation\Rules\Core\IsFalse::class,
    'is_null' => \Engine\Core\Validation\Rules\Core\IsNull::class,
    'is_true' => \Engine\Core\Validation\Rules\Core\IsTrue::class,
    'is_abs' => \Engine\Core\Validation\Rules\Core\IsPositiveNumber::class,
    'int' => \Engine\Core\Validation\Rules\Core\IsInteger::class,
    'num' => \Engine\Core\Validation\Rules\Core\IsNumber::class,
    'kpp' => \Engine\Core\Validation\Rules\Core\Kpp::class,
    'length' => \Engine\Core\Validation\Rules\Core\Length::class,
    'min' => \Engine\Core\Validation\Rules\Core\Min::class,
    'max' => \Engine\Core\Validation\Rules\Core\Min::class,
    'less_than' => \Engine\Core\Validation\Rules\Core\LessThan::class,
    'less_than_or_equal' => \Engine\Core\Validation\Rules\Core\LessThanOrEqual::class,
    'not_blank' => \Engine\Core\Validation\Rules\Core\NotBlank::class,
    'not_equal_to' => \Engine\Core\Validation\Rules\Core\NotEqualTo::class,
    'not_identical_to' => \Engine\Core\Validation\Rules\Core\NotIdenticalTo::class,
    'not_null' => \Engine\Core\Validation\Rules\Core\NotNull::class,
    'ogrn' => \Engine\Core\Validation\Rules\Core\Ogrn::class,
    'okpo' => \Engine\Core\Validation\Rules\Core\Okpo::class,
    'range' => \Engine\Core\Validation\Rules\Core\Range::class,
    'is_in' => \Engine\Core\Validation\Rules\Core\IsIn::class,
    'snils' => \Engine\Core\Validation\Rules\Core\Snils::class,
    'sometimes' => \Engine\Core\Validation\Rules\Core\Sometimes::class,
    'time' => \Engine\Core\Validation\Rules\Core\Time::class,
    'until_first_failure' => \Engine\Core\Validation\Rules\Core\UntilFirstFailure::class,
    'url' => \Engine\Core\Validation\Rules\Core\Url::class
];
